name: run-script

on:
  schedule:
    - cron: "0 */6 * * *"  # cada 6 horas

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Python
        run: python script.py